### ISSUE TITLE
Sidebar overlaps with main content

### ISSUE THREAD

**Issue by cpawley** [ECFMP/flow#121]
![image](https://user-images.githubusercontent.com/7559173/177056150-14e3f4c9-579d-4925-9c5f-884e7d68090b.png)

On this URL: https://ecfmp.vatsim.net/dashboard/flight-information-regions?tableSortColumn=identifier&tableSortDirection=asc

The Content of the window overlaps with the menu

**Comment by NelisV** [comment]
UI centers on whole screen width, and not screen width minus the width of the sidebar.

**Comment by Marceijkens** [comment]
Behavior is also observed in Chrome.

**Comment by daveroverts** [comment]
Bug might have been introduced in https://github.com/ECFMP/flow/commit/0a6a493ba7a639305192ed9c92fe89a53886a212 when adding custom styling (specific colors).

Note 2 self: Check if this can be solved by enabling [collapsible sidebar on desktop](https://filamentphp.com/docs/2.x/admin/appearance#collapsible-sidebar) or by re-trying custom theme setup

**Comment by daveroverts** [comment]
#128 somehow didn't solve this issue, I'll have to re-check
