### ISSUE TITLE
Unable to select event active now

### ISSUE THREAD

**Issue by KHardern** [ECFMP/flow#138]
Event just created to start in 2 minutes from now and I'm unable to create a flow measure from it.

I can create a flow measure and link an event created an hour in advance.

Correct functionality would be for flow measures to be able to be assigned for up to an hour (or two if you want) after an event.

**Comment by daveroverts** [comment]
@KHardern I can't reproduce this issue. Can you provide the exact steps?

**Comment by KHardern** [comment]
I can't either now. I know this was on a list 2 weeks ago, so perhasp you already fixed it and it wasn't yet in the beta... or perhaps I was doing something odd. 

Closing
