### ISSUE TITLE
Active Flow Measure Edit

### ISSUE THREAD

**Issue by NickMarinov** [ECFMP/flow#164]
Can not edit the value of the active flow measure on the edit page (e.g. change from 15nm in trail to 20nm in trail).

Should be able to do so, but not change the type of flow measure itself.

**Comment by KHardern** [comment]
![image](https://user-images.githubusercontent.com/6871785/178596726-3e42d79e-1af9-4d6c-875f-a1c5d660ace5.png)

https://ecfmp.vatsim.net/dashboard/flow-measures/33
Can confirm. I'm unable to edit the MIT as well.

@daveroverts 
UI doesn't let the box be edited. The one above is an active flow measure, however the value shoudl be editable for all types.
