### ISSUE TITLE
Mandatory Route - deleting boxes

### ISSUE THREAD

**Issue by KHardern** [ECFMP/flow#167]
![image](https://user-images.githubusercontent.com/6871785/179374536-fff5d97c-5656-4425-8ce9-0e43c45917e5.png)

When deleting one of the mandatory route boxes, it creates several unformatted textboxes in it's place.

**Comment by daveroverts** [comment]
Possibly caused by Cloudflare's Auto Minify on HTML.

**Comment by daveroverts** [comment]
Disregard last comment, something else is causing errors.
