### ISSUE TITLE
Slot CSVs & API

### ISSUE THREAD

**Issue by KHardern** [ECFMP/flow#176]
A current major issue with the vatcan slot plugin is that it only goes by CID submitted. To be 'event traffic' most of the time a departure/arrival field would be known for a slot. 

Suggest enhancement that we add (optional) ICAO code for departure and arrival as part of CSV upload and available in API.

**Comment by NelisV** [comment]
Question: what will be the impact to the event/non event flow measure filters. Will it be seen as 'event traffic' with just the CID in the list? or do the CID's ADEP and ADES need to match? --> needs to be described in the docs if we implement this.

**Comment by KHardern** [comment]
@daveroverts Would require the CSV uploader for participants to be:

CID, DEP, ARR
1010573, EGLL, EIDW

With DEP and ARR allowed to be null.
New table required for this in DB

@AndyTWF to update API. Keep v1
