### ISSUE TITLE
!ADEP Logic: Ground Stop (UI)

### ISSUE THREAD

**Issue by KHardern** [ECFMP/flow#183]
Planned as part of ADEP logic changes.

Add flow measure "Ground stop" (ground_stop). Requires no value. Requires ADES to be airport group, or custom value with at least 2 characters (e.g. EI**, EID*, EIDW). 

~~"FAO" should ideally be allowed to be left blank for this flow measure only.~~

**Comment by KHardern** [comment]
@daveroverts Ignore the FAO remaining blank. Leave FAO as mandatory for all measures (for now).

**Comment by KHardern** [comment]
I think this is done? @daveroverts

**Comment by daveroverts** [comment]
@KHardern This was already merged in #175 2 days before this issue got created
