### ISSUE TITLE
ADEP Logic: Ground Stop (API & Discord)

### ISSUE THREAD

**Issue by KHardern** [ECFMP/flow#184]
Planned as part of ADEP logic changes.

Type ground_stop to be added to the API. When processing for discord tags, if no FAOs submitted, tag "@here".
Note: for notifications/documentation "Ground Stop" is stylized as 2 words, no hyphen

For how we do this in the API, we probably need some discussions. Options are:

1) a blank "FAO" includes all FIRs in the API
2) we create 'groups' or 'regions' in the FIR tables and use this as logic of who to tag (a possible enhancement anyway in the future, given we've now expanded to Middle East)
3) we define it as an exception to the logic for being able to filter by tag
4) we make the FIR code in the API "0" (zero) and define this as meaning applicable to everyone

**Comment by KHardern** [comment]
As a side-note, I'm tempted to say that a ground-stop does the @here notification even if there are FAOs selected. Thoughts Andy?

**Comment by AndyTWF** [comment]
`@here` is easy enough to add, very glad I split this out into separate classes xD

Will think a bit!

**Comment by KHardern** [comment]
Discussed in meeting. Will re-open when have discussed how to tag FABs/Blocks/adjacents
