### ISSUE TITLE
Configure Discord for Launch

### ISSUE THREAD

**Issue by KHardern** [ECFMP/flow#204]
1. Archive old flow measures channel
2. Create new flow measures channel (not announcement) with webhook
3. #system-questions channel (or similar name)
4. migrate database to dev site, new database for live site
5. update dev area to use current version (and vatsim connect)
6. grant permissions
7. announce launch

**Comment by NelisV** [comment]
- [ ]    Archive old flow measure channel
- [ ]     Create new flow measures channel (not announcement) with webhook
- [ ]     #system-questions channel (or similar name)
- [ ]     migrate database to dev site, new database for live site
- [ ]     update dev area to use current version (and vatsim connect)
- [ ]     grant permissions
- [ ]     announce launch
